use std::collections::{HashMap, HashSet};


impl Solution {
    pub fn calc_equation(
            equations: Vec<Vec<String>>,
                    values: Vec<f64>,
                            queries: Vec<Vec<String>>,
                                ) -> Vec<f64> {

                                        // Graph:
                                                // a -> [(b, 2.0)]
                                                        // b -> [(a, 0.5)]
                                                                let mut graph: HashMap<String, Vec<(String, f64)>> = HashMap::new();

                                                                        for (eq, &value) in equations.iter().zip(values.iter()) {
                                                                                    let a = &eq[0];
                                                                                                let b = &eq[1];

                                                                                                            graph.entry(a.clone())
                                                                                                                            .or_default()
                                                                                                                                            .push((b.clone(), value));

                                                                                                                                                        graph.entry(b.clone())
                                                                                                                                                                        .or_default()
                                                                                                                                                                                        .push((a.clone(), 1.0 / value));
                                                                                                                                                                                                }

                                                                                                                                                                                                        queries
                                                                                                                                                                                                                    .iter()
                                                                                                                                                                                                                                .map(|q| {
                                                                                                                                                                                                                                                let start = &q[0];
                                                                                                                                                                                                                                                                let end = &q[1];

                                                                                                                                                                                                                                                                                // Variable missing
                                                                                                                                                                                                                                                                                                if !graph.contains_key(start) || !graph.contains_key(end) {
                                                                                                                                                                                                                                                                                                                    return -1.0;
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                    // Same variable
                                                                                                                                                                                                                                                                                                                                                                    if start == end {
                                                                                                                                                                                                                                                                                                                                                                                        return 1.0;
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                        let mut visited = HashSet::new();

                                                                                                                                                                                                                                                                                                                                                                                                                                        Self::dfs(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            &graph,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                start,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    end,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1.0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            &mut visited,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).unwrap_or(-1.0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .collect()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fn dfs(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    graph: &HashMap<String, Vec<(String, f64)>>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            current: &String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    target: &String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            product: f64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    visited: &mut HashSet<String>,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) -> Option<f64> {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if current == target {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return Some(product);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            visited.insert(current.clone());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if let Some(neighbors) = graph.get(current) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (next, weight) in neighbors {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if visited.contains(next) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if let Some(result) = Self::dfs(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        graph,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            next,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    product * weight,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        visited,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return Some(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }